# Generated by Django 3.2.12 on 2022-03-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='nick_name',
            new_name='username',
        ),
    ]
