# Generated by Django 3.2.12 on 2022-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0002_rename_nick_name_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(help_text='Optional.', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(help_text='Optional.', max_length=30),
        ),
    ]
