# Generated by Django 3.2.12 on 2022-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0003_auto_20220329_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.CharField(default='pedestrian', max_length=10),
        ),
    ]
