# Generated by Django 3.2.12 on 2022-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0004_usermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('pedestrian', 'PEDESTRIAN'), ('editor', 'EDITOR')], default='pedestrian', max_length=10),
        ),
    ]
