# Generated by Django 3.2.12 on 2022-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0005_alter_usermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('editor', 'EDITOR'), ('pedestrian', 'PEDESTRIAN')], default='pedestrian', max_length=10),
        ),
    ]
