# Generated by Django 3.2.12 on 2022-04-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0007_rename_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pedestrian', 'PEDESTRIAN'), ('editor', 'EDITOR')], default='pedestrian', max_length=10),
        ),
    ]
