# Generated by Django 3.2.12 on 2022-04-06 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0012_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('article', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pedestrian', 'PEDESTRIAN'), ('editor', 'EDITOR')], default='pedestrian', max_length=10),
        ),
    ]
