# Generated by Django 3.2.12 on 2022-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0013_auto_20220406_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('editor', 'EDITOR'), ('pedestrian', 'PEDESTRIAN')], default='pedestrian', max_length=10),
        ),
    ]
