# Generated by Django 3.2.12 on 2022-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0015_alter_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='username',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('editor', 'EDITOR'), ('pedestrian', 'PEDESTRIAN')], default='pedestrian', max_length=10),
        ),
    ]
