# Generated by Django 3.2.12 on 2022-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0016_auto_20220406_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='article_permission',
            field=models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default='public', max_length=35),
        ),
    ]
